### ISSUE TITLE
TypeError: Cannot read property 'children' of null

### ISSUE THREAD

**Issue by Ryuzaki-3301** [GalacticBot/modmail#2]
Hey!
I was trying to run the bot on a server and then this happened.
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'children' of null
    at ChannelHandler.sweepChannels (/home/container/structure/ChannelHandler.js:214:50)
    at listOnTimeout (internal/timers.js:555:17)
    at processTimers (internal/timers.js:498:7)

**Comment by Navy-gif** [comment]
Have you configured the modmailCategory setting in options.js?
It should have 3 categories in it, obviously they need to exist too and the bot needs access to them.

This is a part of the set-up process I've yet to automate.

**Comment by Ryuzaki-3301** [comment]
Yes, it was configured. and yes they did exist too.
I suppose by options.js you mean config.js. If not, please link me the directory. Thanks :D

**Comment by Navy-gif** [comment]
Sorry yeah, I meant config.js

Could you double check the bot's permissions and confirm it has access to manage the categories?
I'll add some further error handling to this but I can't think of any other reason that part would error.

I'll post another comment here once I've updated the code with the error handling.

**Comment by Navy-gif** [comment]
I updated the code with more outputs, pull the latest update and let me know if you're still experiencing the issue.

**Comment by Ryuzaki-3301** [comment]
Will do, thank you!

**Comment by Navy-gif** [comment]
Assuming this issue was resolved with the update given the lack of updates so I'm closing this.
